services:
  postgresql:
    image: bitnami/postgresql
    env_file: config/config.env
    volumes:
      - pgsql-data:/bitnami/postgresql
    ports:
      - 5432:5432
  redis:
    image: bitnami/redis
    env_file: config/config.env
    volumes:
      - redis-data:/bitnami/redis/data
  minio:
    image: minio/minio
    env_file: config/config.env
    volumes:
      - minio-data:/data
  frontend:
    build: ./frontend
    env_file: config/config.env
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app:ro
  storage:
    build: ./storage
    env_file: config/config.env
  engine:
    build: ./engine
    env_file: config/config.env
  workflow:
    build: ./workflow
    env_file: config/config.env
volumes:
  redis-data:
  pgsql-data:
  minio-data:
