name: clarifier_development
services:
  postgresql:
    image: bitnami/postgresql
    env_file: development.env
    volumes:
      - pgsql-data:/bitnami/postgresql
    ports:
      - 5432:5432
  redis:
    image: bitnami/redis
    env_file: development.env
    volumes:
      - redis-data:/bitnami/redis/data
  minio:
    image: minio/minio
    env_file: development.env
    volumes:
      - minio-data:/data
    command:
      - server
      - /data
      - --console-address
      - ":9001"
  clickhouse:
    image: clickhouse/clickhouse-server
    env_file: development.env
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ports:
      - 8123:8123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  frontend:
    restart: always
    depends_on:
      - backend
    build: ./frontend
    env_file: development.env
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: rebuild
          path: ./frontend/bun.lockb
  backend:
    restart: always
    depends_on:
      - postgresql
      - redis
      - minio
    build: ./backend
    env_file: development.env
    environment:
      DEBUG: "True"
    develop:
      watch:
        - action: sync
          path: ./backend/backend
          target: /usr/src/backend
        - action: rebuild
          path: ./backend/poetry.lock
    ports:
      - 8000:8000
  backend_worker:
    restart: always
    depends_on:
      - postgresql
      - redis
      - minio
    build: ./backend
    env_file: development.env
    environment:
      DEBUG: "True"
    develop:
      watch:
        - action: sync+restart
          path: ./backend/backend
          target: /usr/src/backend
        - action: rebuild
          path: ./backend/poetry.lock
    command:
      - /usr/src/backend/manage.py
      - rqworker
      - --with-scheduler
      - default
      - sources
      - workflows
      - workspace
      - profiling
volumes:
  redis-data:
  pgsql-data:
  minio-data:
  clickhouse-data:
