# Generated by Django 5.1.1 on 2024-11-18 12:53

from django.db import migrations, models


def populate_workspace(apps, schema_editor):
    Workspace = apps.get_model("workspace", "Workspace")

    # Create DimensionGroup
    Workspace.objects.create(name="default", description="Default Workspace")


def rollback_workspace(apps, schema_editor):
    Workspace = apps.get_model("workspace", "Workspace")
    # Get the group to delete dimensions and the group itself
    try:
        workspace = Workspace.objects.get(name="default")
        workspace.delete()
    except Workspace.DoesNotExist:
        pass


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RunPython(
            populate_workspace,
            rollback_workspace,
        ),
    ]
